/**
 * Validates the functionality provided by the ContactDeDupWS class.
 *
 * @author  Shawn Gray
 * @version 2013-07-22
 */

/**
 * CHANGE HISTORY
 * =============================================================================
 * Date         Name                    Description
 * 2013-07-22   Shawn Gray              Created                                                                   
 * =============================================================================
 */
@IsTest(seealldata = true)

public class ContactDeDupWS_Test {


}