/**
 * Validates the functionality provided by the InformaticaAddressCleanse_WSobject class.
 *
 * @author   Nandita Shet
 * @version  2014-07-14
 */

/**
 * CHANGE HISTORY
 * =============================================================================
 * Date          Name                Description
 * 2012-05-15    Nandita Shet        Created
 * =============================================================================
 */
@IsTest

private class InformaticaAddressCleanse_WSObject_Test {



}