@isTest
public class OnlineContactsSerandDeserReqResTest {
    public static testMethod void OnlineContacts() {
        OnlineContactsSerializeandDeserializeReq ocSD = new OnlineContactsSerializeandDeserializeReq();
        OnlineContactsSerializeandDeserializeReq.OnlineContactsRequest ocReq = new OnlineContactsSerializeandDeserializeReq.OnlineContactsRequest();
        OnlineContactsSerializeandDeserializeRes.OnlineContactResponse ocRes = new OnlineContactsSerializeandDeserializeRes.OnlineContactResponse();
        OnlineContactsSerializeandDeserializeRes.NotificationResponse noteRes = new OnlineContactsSerializeandDeserializeRes.NotificationResponse();
        OnlineContactsSerializeandDeserializeRes.onlineContact oc = new OnlineContactsSerializeandDeserializeRes.onlineContact();
        OnlineContactsSerializeandDeserializeRes.entitlements entl = new OnlineContactsSerializeandDeserializeRes.entitlements();
        OnlineContactsSerializeandDeserializeRes.Notification note = new OnlineContactsSerializeandDeserializeRes.Notification();
    }
}